# Generated by Django 4.1.1 on 2022-09-12 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='book_name',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='library',
            name='book_issued',
        ),
        migrations.RemoveField(
            model_name='library',
            name='number',
        ),
        migrations.AlterField(
            model_name='library',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=255)),
                ('issued_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.library')),
            ],
        ),
    ]
